auth:
  WebAppInit: ""
  tokenFile: "tokens.json"
  folder: "config"

settings:
  daemon: false         # Run perpetually (restart every 8 hrs)
  randomAgent: true     # Randomise User-Agent
  delay: 3              # Delay between tasks (in seconds)
  tasks: true           # Enable or disable task automation
  farming: true         # Enable or disable farming claims
  gaming: true          # Enable or disable gaming automation